In [2]:
!pip install pandas numpy faiss-cpu sentence-transformers scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Collecting faiss-cpu
  Downloading faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.6 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.10.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)
Downloading faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (23.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 55.7 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.13.2

In [3]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/AmazonDataset/7817_1.csv')

In [4]:
# Keep only required columns
df = df[['asins', 'name', 'reviews.text', 'reviews.rating']]

In [5]:
# Drop missing reviews
df = df.dropna(subset=['reviews.text'])

In [6]:
# Reset index
df = df.reset_index(drop=True)

print("Shape:", df.shape)
df.head()

Shape: (1597, 4)

,asins,name,reviews.text,reviews.rating
0,B00QJDU3KY,Kindle Paperwhite,I initially had trouble deciding between the p...,5.0
1,B00QJDU3KY,Kindle Paperwhite,Allow me to preface this with a little history...,5.0
2,B00QJDU3KY,Kindle Paperwhite,I am enjoying it so far. Great for reading. Ha...,4.0
3,B00QJDU3KY,Kindle Paperwhite,I bought one of the first Paperwhites and have...,5.0
4,B00QJDU3KY,Kindle Paperwhite,I have to say upfront - I don't like coroporat...,5.0

In [7]:
df.info()
df.isnull().sum()
df['reviews.rating'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1597 entries, 0 to 1596
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   asins           1597 non-null   object
 1   name            1597 non-null   object
 2   reviews.text    1597 non-null   object
 3   reviews.rating  1177 non-null   float64
dtypes: float64(1), object(3)
memory usage: 50.0+ KB

reviews.rating
5.0    741
4.0    236
3.0    124
1.0     42
2.0     34
Name: count, dtype: int64

In [10]:
# Clean the text
import re
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    return text

df['clean_review'] = df['reviews.text'].apply(clean_text)

In [ ]:
"""
1. Vector Representation of Data
Convert each customer review into a vector (embedding) using any embedding model.
This helps represent the meaning of the text numerically.

"""

In [11]:
from sentence_transformers import SentenceTransformer

#Load the model
model=SentenceTransformer('all-MiniLM-L6-v2')

#Convert the reviews into vectors
embeddings=model.encode(df['clean_review'].tolist(),show_progress_bar=True)

print(embeddings.shape)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/50 [00:00<?, ?it/s]

(1597, 384)

In [ ]:
"""
2. Introduction to Vector DB
Store all embeddings in a Vector Database (you can use FAISS as a simple implementation).
Each entry should contain:
Review text
Vector embedding

"""

In [14]:
# Store in FAISS (Vector DB)
import faiss
import numpy as np

#Convert the data to numpy Array
embeddings=np.array(embeddings).astype('float32')

# Create Index
dimension=embeddings.shape[1]
index=faiss.IndexFlatL2(dimension)

#Add Vectors to Index
index.add(embeddings)

print("total vectors in index: ",index.ntotal)

total vectors in index:  1597

In [20]:
# Building the search function
def search_reviews(query, k=5):
    # Convert the query into vector
    query_vec=model.encode([query])
    query_vec=np.array(query_vec).astype('float32')

    # Normalize query
    #faiss.normalize_L2(query_vec)

    # Search in FAISS
    distances, indices=index.search(query_vec, k)

    # Get results
    results=df.iloc[indices[0]][['reviews.text','reviews.rating']]
    return results

In [21]:
# Testing the semantic Search
query="battery drains fast"
results = search_reviews(query)

for i, row in results.iterrows():
  print("Review:",row['reviews.text'])
  print("Rating:",row['reviews.rating'])
  print("-"*50)

Review: ..exactly what I wanted, but the battery drains FAST when on hands free mode.
Rating: 4.0
--------------------------------------------------
Review: I've had the Kindle Fire HDX 7 inch tablet for almost 3 years and when I compare it to the Fire HD 10, the earlier tablet comes out the big winner. I find the larger tablet considerably slower. Several apps load quite slowly. The battery is consumed much more quickly. Maybe this is not comparing apples with apples, but I had expected at least the same speed.
Rating: 3.0
--------------------------------------------------
Review: First off,i appreciate you reading this review :) Just so you get a little background on me, we are major tech users. We have multiple tablets from apple,samsung,and asus. This fire tablet is comparable in a different way. This tablet uses a amazon based operating system, Fire os. So no play store or itunes... As a prime member however, this tablet is an incredible value because you get instant access to all of your prime benifits. Ive had a chance to really put this product thru its paces over the past 2 days. I ordered 2 of these tablets so me and my wife could really put these to use. We have Gone thru 3 full power cycles (fully charging and fully draining the battery thru use) it does get 10-11 hours of hefty use so battery life is a plus! This tablet is a keeper. Screen looks fantastic. Colors seem to be just slightly dull however the resoloution for everyday use is perfect for this price point. Speed is snappy enough for basic use and handles more complex tasks and games without much issue. On a passmark benchmark test i got a score of 3377. However the second HD 8 constantly grades about 30-35 points lower. So it is a possibility that even tho you have the same exact tablet,they might be built slightly different so performance will vary. At this price point I didnt expect them to come out exactly the same. This tablet is bassically the same specs as the samsung tab a at half the price! Oh and the hd 8 actually offers a slightly better resoloution then the samsung! Minus one star for the wifi connection. I have lost connection several times on both tablets. Seems to only happen on my 5g connection.Also the screen being so reflective,it is impossible to use at all outdoors.also sadly is a fingerprint magnet.Read more
Rating: 4.0
--------------------------------------------------
Review: good speaker. 8 hour battery. Good price. Excellent quality in how it is made.
Rating: 5.0
--------------------------------------------------
Review: First, let me say that this is my first Fire tablet. I've previously had either iPad's or Android tablets. I was skeptical at first because I've generally only liked iPad's, but I decided to give it a try and I'm glad I did. I paid full price for this product and am not being compensated in any manner to post this review.Let's just jump right to the Pro's and Con's shall wePro's:FastAmazing Screen resolutionGreat soundResponsiveAlexa is kind of awesomeBattery life. OMG! I've charged it once so far, I've watched YouTube videos on it, streamed a movie and a few TV shows and I use it for Facebook and I'm not even half way down on the battery after 3 days. Wow!The OS. The operating system is simple, responsive, and beautifully done. Everything is easy to find and it's really easy to navigate.Con's:Only one Con...Charge port. The charge port is sticky and doesn't seem as high quality.Overall this is a fantastic tablet and worth so much more than the price. I LOVE IT!
Rating: 5.0
--------------------------------------------------

In [25]:
# Keyword Search
def keyword_search(query, k=5):
  results=df[df['clean_review'].str.contains(query.lower(), na=False)]
  return results[['reviews.text','reviews.rating']].head(k)

In [26]:
# Compare semantic search with Keyword Search
query="battery drains fast"
print("Keyword Search Results:")
print(keyword_search(query))

print("\nSemantic Search Results:")
print(search_reviews(query))

Keyword Search Results:
                                          reviews.text  reviews.rating
979  ..exactly what I wanted, but the battery drain...             4.0

Semantic Search Results:
                                           reviews.text  reviews.rating
979   ..exactly what I wanted, but the battery drain...             4.0
244   I've had the Kindle Fire HDX 7 inch tablet for...             3.0
670   First off,i appreciate you reading this review...             4.0
1309  good speaker. 8 hour battery. Good price. Exce...             5.0
556   First, let me say that this is my first Fire t...             5.0